/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.patientapigateway.client.patient.api;

import com.bytatech.ayoos.patientapigateway.client.patient.model.MedicalRecordsDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-11-19T15:09:32.027+05:30[Asia/Calcutta]")

@Api(value = "MedicalRecordsResource", description = "the MedicalRecordsResource API")
public interface MedicalRecordsResourceApi {

    @ApiOperation(value = "createMedicalRecords", nickname = "createMedicalRecordsUsingPOST", notes = "", response = MedicalRecordsDTO.class, tags={ "medical-records-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = MedicalRecordsDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/medical-records",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<MedicalRecordsDTO> createMedicalRecordsUsingPOST(@ApiParam(value = "medicalRecordsDTO" ,required=true )  @Valid @RequestBody MedicalRecordsDTO medicalRecordsDTO);


    @ApiOperation(value = "deleteMedicalRecords", nickname = "deleteMedicalRecordsUsingDELETE", notes = "", tags={ "medical-records-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/medical-records/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteMedicalRecordsUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllMedicalRecords", nickname = "getAllMedicalRecordsUsingGET", notes = "", response = MedicalRecordsDTO.class, responseContainer = "List", tags={ "medical-records-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = MedicalRecordsDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/medical-records",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<MedicalRecordsDTO>> getAllMedicalRecordsUsingGET(@ApiParam(value = "") @Valid @RequestParam(value = "offset", required = false) Long offset,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "") @Valid @RequestParam(value = "pageNumber", required = false) Integer pageNumber,@ApiParam(value = "") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "") @Valid @RequestParam(value = "paged", required = false) Boolean paged,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort,@ApiParam(value = "") @Valid @RequestParam(value = "sort.sorted", required = false) Boolean sortSorted,@ApiParam(value = "") @Valid @RequestParam(value = "sort.unsorted", required = false) Boolean sortUnsorted,@ApiParam(value = "") @Valid @RequestParam(value = "unpaged", required = false) Boolean unpaged);


    @ApiOperation(value = "getMedicalRecords", nickname = "getMedicalRecordsUsingGET", notes = "", response = MedicalRecordsDTO.class, tags={ "medical-records-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = MedicalRecordsDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/medical-records/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<MedicalRecordsDTO> getMedicalRecordsUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchMedicalRecords", nickname = "searchMedicalRecordsUsingGET", notes = "", response = MedicalRecordsDTO.class, responseContainer = "List", tags={ "medical-records-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = MedicalRecordsDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/medical-records",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<MedicalRecordsDTO>> searchMedicalRecordsUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "") @Valid @RequestParam(value = "offset", required = false) Long offset,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "") @Valid @RequestParam(value = "pageNumber", required = false) Integer pageNumber,@ApiParam(value = "") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,@ApiParam(value = "") @Valid @RequestParam(value = "paged", required = false) Boolean paged,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort,@ApiParam(value = "") @Valid @RequestParam(value = "sort.sorted", required = false) Boolean sortSorted,@ApiParam(value = "") @Valid @RequestParam(value = "sort.unsorted", required = false) Boolean sortUnsorted,@ApiParam(value = "") @Valid @RequestParam(value = "unpaged", required = false) Boolean unpaged);


    @ApiOperation(value = "updateMedicalRecords", nickname = "updateMedicalRecordsUsingPUT", notes = "", response = MedicalRecordsDTO.class, tags={ "medical-records-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = MedicalRecordsDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/medical-records",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<MedicalRecordsDTO> updateMedicalRecordsUsingPUT(@ApiParam(value = "medicalRecordsDTO" ,required=true )  @Valid @RequestBody MedicalRecordsDTO medicalRecordsDTO);

}
